name=SparkFun HowTo Arduino Library
version=1.0.0
author=SparkFun Electronics <techsupport@sparkfun.com>
maintainer=SparkFun Electronics <https://www.sparkfun.com>
sentence=A repo that provide a "how to" setup a SparkFun Arduino Library repository.
paragraph=Provides an example of how to setup a SparkFun Arduino Library repository. This library is not meant to be used in production, but rather as a reference for how to setup a SparkFun Arduino Library repository.
category=demo
url=https://github.com/sparkfun/SparkFun_MCP4725_Arduino_Library
architectures=*
depends=SparkFun Toolkit
includes=SparkFun_HowTo_Arduino_Library.h
